services:
  web-browser:
    image: alpine
    networks:
      - public-net
    command: sleep infinity

  frontend-proxy:
    image: nginx:alpine
    networks:
      - public-net
      - private-net

  secure-database:
  image: postgres:alpine
  environment:
    POSTGRES_PASSWORD: ${DB_PASSWORD}
  networks:
    - private-net

  security-monitor:
    image: alpine
    volumes:
      - .:/logs
    networks:
      - private-net
    command: sh -c "chmod +x /logs/monitor.sh && /logs/monitor.sh"

  honeypot:
    image: cowrie/cowrie:latest
    container_name: fortress-honeypot
    ports:
      - "2222:2222"
    networks:
      - public-net
    restart: always

networks:
  public-net:
    driver: bridge
  private-net:
    internal: true