name: Security Scan
on: [push]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          # Scans the root directory for docker-compose and k8s files
          directory: .
          # Using specific frameworks prevents the "argument error"
          framework: docker_compose,kubernetes 
          quiet: true # Shows only failed checks to keep logs clean
