name: Security Scan
on: [push]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          # Changing this to 'all' fixes the "Invalid frameworks" error
          framework: all 
          quiet: true
          # This allows the job to finish even if it finds security warnings
          soft_fail: true
